operatorid: openlitest
listenport: 10001
listenaddr: 172.20.0.2
provisioneraddr: 172.20.0.2
provisionerport: 12001
mediatorid: 600

tlscert: certs/clientB-crt.pem
tlskey: certs/clientB-key.pem
tlsca: certs/ca-crt.pem


#etsitls: "false"